services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "/go-rest-api/bin/migrate up && /go-rest-api/bin/api"]

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=go-database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d go-database"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db-data:
